### ISSUE TITLE
🛠 Roadmap

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent#125]
Let's get a roadmap of what features contributors and users think are important for Fluent 1.1 and Fluent 2.0. 

Fluent 1.1
- [x] Improved Testing
- [x] Improved Unions
  - [x] Work with modifying and deleting.
  - [ ] Pre-load relational models

Fluent 2.0
- [x] Timestamps
- [x] Siblings relation needs Left and Right entities (as well as other relations)
- [x] Allow custom fields on Pivots.
- [x] Relation `attach` and `detach`
- [ ] Fetch subset of data

Comment below with any ideas you have or things you would change or add to this list.

**Comment by sroebert** [comment]
- `UUID` support for ID's (or in general any type as an ID)
- More options for fields (unique, foreign keys `ON DELETE` actions)

**Comment by mludi** [comment]
- Faker-Support (something like https://github.com/fzaninotto/Faker) or seeds

**Comment by sroebert** [comment]
I was already looking into this one and it doesn't seem easy to provide it properly for all kinds of drivers, but anyway:
- Support for filtering `IN` a subquery. (e.g. `SELECT * FROM users WHERE username IN (SELECT username FROM some_other_table). One step closer would already be if there is an ability to perform a raw query and return a specific `Entity`.

**Comment by sroebert** [comment]
- Support for transactions, basically allowing multiple queries to be performed in a single transaction and possibly rolled back.

**Comment by jumbofish** [comment]
I'm new to vapor/fluent and still not clear on how migrations work.  I see preparations, but they seem different than a migration.  Either migrations or documentation on how preparations solve the problem.

**Comment by sroebert** [comment]
- `Date` support.

**Comment by clapton101** [comment]
These are all the base types that Active Record supports. It would be nice if they could all be handled by fluent. Given that Active Record is also DB agnostic at this layer, it seems that it would be possible to implement all of them in fluent as well.
* Boolean
* String (char)
* Binary
* Text
* Date
* Time
* DateTime
* Float
* Integer

Additionally these types are aliased:
* blob => "binary"
* clob => "text"
* timestamp => "datetime"
* numeric => "decimal"
* number => "decimal"
* double => "float"

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L496-L512

Personally, the absence of support for any type of datetime in fluent is a major road block to the adoption of Vapor.

**Comment by sroebert** [comment]
I am wondering with the support for more types in mind (e.g. UUID, Date, Time), how would this be implemented without changing `Node`, which I can imagine should not really be changed. It would not be incredibly performant to have to convert between different types all the time. It would be nicer to be able to use `Date` and `UUID` directly.

**Comment by LoganWright** [comment]
@sroebert that is correct about changing Node.

We should ideally focus on features that can be achieved w/o too much modification. It is meant to be extremely agnostic, so each addition should be approached very carefully, but we should also be open to the idea in more forward looking ideas as we eye 2.0.

**Comment by yuriferretti-luizalabs** [comment]
Bulk modifications  using syntax `update(field: String, value: Node) `
```swift
User.all()update(field: "active", value: false)
```

**Comment by bygri** [comment]
This may already be implemented—if so, I can't find it—but the ability to iterate over large result sets without loading the whole set of model instances into memory as per `all()`. In other words, keeping hold of the query cursor so a series of `fetchNext()` calls can be made.

**Comment by maximedegreve** [comment]
Support for RAND()

**Comment by fwgreen** [comment]
Improved error messages.  Errors like `Fluent.RelationError error 0` don't provide much guidance.

**Comment by steve-h** [comment]
Fluent:
```swift
public static var name: String {
        return String(describing: self).lowercased()
    }
```
 instead of the name I gave the api:
I originally used database.create("commentaries")

```swift
extension Commentary: Preparation {
    static func prepare(_ database: Database) throws {
        try database.create("commentarys") { document in  //3hrs debug to find MySQL need 's' added to commentary not commentaries
            document.id()
```

apparently a common Rails trap too.

**Comment by califrench** [comment]
I think something that would be very useful is lazily loading resulting models.
Right now queries on large numbers of models are quite expensive both in CPU and memory but lazily loading models by leveraging an intermediary class would drastically improve the performance.

This is a functionality that is found in ORMs such as Doctrine and Active Record.

**Comment by cwoloszynski** [comment]
Sounds like a great addition!

**Comment by califrench** [comment]
Specifically for the lazy loading, what needs to be looked at is line 69 in `Query.swift`:

```swift
let model = try T(node: result, in: _context)
```

I think it's very common for web applications to perform queries on thousands of items, and often the models only need to be instantiated when iterated over.

I need to play around with a possible intermediary class that represents the uninstantiated entity to see if it would help. However, the downsides of lazy loading are the added overhead of storing the raw query results somewhere and the hassle of dealing with entities that are possibly loaded or possibly not...

I'm curious if the rest of the community is interested in this?

**Comment by bygri** [comment]
My [attempted solution](https://github.com/vapor/mysql/pull/77) was to still instantiate the model directly from the query, but only iteratively, so only one model object is loaded at a time. I think it's a fair middle ground. I could not myself think of any situation where this solution would not fit - filtering, offsets, limiting are generally better done on the database end, and could still done iteratively if really necessary.

**Comment by tanner0101** [comment]
Closing this as we are nearing 2.0s release. Please feel free to open new issues for any features you'd like to see in the coming versions. Thanks!
